Task bodies
elixir-cloud-aai/protes-middleware-crypt4gh pull request #1
Opened 2024-05-22 18:44 UTC by athith-g

I have created three TES tasks (and their associated tests):

- **Task 1**: Take the contents of an input file and produce an output file with an uppercase version of the contents.
- **Task 2**: Take the contents of a _Crypt4GH-encrypted_ input file and produce an output file with the decrypted contents.
- **Task 3**: Take the contents of a _Crypt4GH-encrypted_ input file and produce an output file with the uppercase version of the contents.

Essentially, I want the middleware to turn Task 1, the [uppercase task](https://github.com/elixir-cloud-aai/protes-middleware-crypt4gh/compare/task_bodies?expand=1#diff-0678a505db851106224932fb167ef35e252624edae41f83cb9cc71583c798ccfR7) (with a crypt4gh file and secret key file as additional inputs), into Task 3, the [uppercase-with-decryption task](https://github.com/elixir-cloud-aai/protes-middleware-crypt4gh/compare/task_bodies?expand=1#diff-0678a505db851106224932fb167ef35e252624edae41f83cb9cc71583c798ccfR80).

I wanted to know if there are any glaring issues with Task 3 before I start hashing out the implementation details of the middleware, since Task 3 is ultimately going to the be the output of the middleware. Is it good enough to get started on the middleware development?

2024-05-28 17:30 UTC, uniqueg requested changes
Very nice! Please add some PRs to build up your repo iteratively with things like `.gitignore`, `README.md`, `Dockerfile`, CI and so on. For inspiration, you can have a look at the work @JaeAeich did (is doing) for his repo (not saying you need all of that, just what seems useful to your case).

It's a bit dull work, but you can learn a lot - and it will pay dividends further on.

2024-05-28 17:30 UTC, uniqueg commented on .gitignore
Consider generating Python-focused `.gitignore` contents, e.g., via GitHub itself, or from [here](https://www.toptal.com/developers/gitignore/) (would give you [theses](https://www.toptal.com/developers/gitignore/api/python) contents). But please do so in a separate PR to keep concerns separate.

2024-05-28 17:30 UTC, uniqueg commented on Dockerfile
Looks fine, but as above, please open separate PRs to keep concerns separate. A PR can never be too small, only too large.

2024-05-28 17:30 UTC, uniqueg commented on README.md
Perhaps add a `README.md` file with an organization-typical top-level structure (e.g., proTES) in a separate PR (leave contents of non-boilerplate sections empty, or put your best guess). Then continuously update it along with other PRs, as required.

2024-05-28 17:30 UTC, uniqueg commented on tests/tasks/test_tasks.py
> +tes_url = "http://localhost:8090/ga4gh/tes/v1"
I think this is fine for now...

2024-05-28 17:30 UTC, uniqueg commented on tests/tasks/test_tasks.py
> +def get_task_state(task_id):
Can add sth like that at a later stage

2024-05-28 23:32 UTC, athith-g commented
Thank you for the suggestions! I broke up this PR into smaller ones, so I'll close this one once all of them are merged.

2024-05-29 01:31 UTC, uniqueg commented
Great job - thanks a lot. Let's get these PRs merged over the next 1-2 days :)

2024-05-30 17:20 UTC, closed without merging