test: add tests for task bodies
elixir-cloud-aai/protes-middleware-crypt4gh pull request #6
Opened 2024-05-28 23:10 UTC by athith-g

Added tests for the previously created task bodies. Will write tests for edge cases in the future.

2024-05-29 01:25 UTC, uniqueg requested changes
Have a look at the open Sourcery AI suggestions and consider using `pytest` to run your test and using `pytest` fixtures to simplify test code.

2024-05-29 01:25 UTC, uniqueg commented on tests/tasks/test_tasks.py
> +    assert post_response.status_code == 200
Consider using `pytest` for running tests. Then, consider defining `pytest` fixtures to simplify the setup stages for your tests to minimize repetition.

I have marked these two lines, but others repeat as well, so possibly those could be included as well in a fixture (or consider having multiple fixtures).

2024-05-30 15:53 UTC, athith-g commented
I've converted the three tests into a single test using fixtures. I'm going to add the edge cases in a different pull request (since it involves adding input files).

2024-05-30 15:59 UTC, uniqueg approved these changes
Fancy! I like :))

2024-05-30 16:00 UTC, uniqueg approved these changes

2024-05-30 16:59 UTC, merged